name: Docker Image CI
on: [push]
jobs:
  build:
    #The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.SERVERNAME }}/meeting_room_reservation:$(date +%s)
      - name: Login
        run: docker login -u ${{ secrets.USERNAME }} --password-stdin ${{ secrets.PASSWORD }} ${{ secrets.SERVERNAME }} 
      - name: Push
        run: docker push ${{ secrets.SERVERNAME }}/meeting_room_reservation:$(date +%s)
